# javascriptをきれいにする
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']

#node.jsの構文チェック
[[plugins]]
repo = 'scrooloose/syntastic'
on_ft = ['javascript']
hook_add = '''
let g:syntastic_check_on_open=0 "ファイルを開いたときはチェックしない
let g:syntastic_check_on_save=1 "保存時にはチェック
let g:syntastic_check_on_wq = 0 " wqではチェックしない
let g:syntastic_auto_loc_list=1 "エラーがあったら自動でロケーションリストを開く
let g:syntastic_loc_list_height=6 "エラー表示ウィンドウの高さ
let g:syntastic_javascript_checkers = ['eslint'] "ESLintを使う
let g:syntastic_mode_map = {
      \ 'mode': 'active',
      \ 'active_filetypes': ['javascript'],
      \ 'passive_filetypes': []
      \ }
'''

#デバッガー
[[plugins]]
repo = 'vim-vdebug/vdebug'
on_ft = ['python']

#go
[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

#tomlファイルをきらびやかに
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

#python整形
[[plugins]]
repo = 'google/yapf'
on_ft = ['python']

